### ISSUE TITLE
Doctrine & properties

### ISSUE THREAD

**Issue by ProklUng** [ericzaev/bitrix-symfony#1]
Properties на приходят почему-то при запросе через Doctrine. Пустой массив. Если важно: 

"Значения свойств хранятся: | в отдельной таблице для данного информационного блока". Когда в общей - приходят.

**Comment by ericzaev** [comment]
Особый случай. Для этого придется [импортировать](https://github.com/ericzaev/bitrix-symfony#%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86-%D0%B1%D0%B8%D1%82%D1%80%D0%B8%D0%BA%D1%81%D0%B0-%D0%B2-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D1%8C-doctrine) таблицу в сущность Doctrine.

Такая-же беда ждет User Fields...

**Comment by ProklUng** [comment]
Да, предельно сложный процесс, изничтожающий идею использования Доктрины. Увы и ах. Как элегантно подключаются и используются модели от Laravel (https://github.com/arrilot/bitrix-models) и как не просто с Доктриной.
